### ISSUE TITLE
Bug: unassigned reference in async message processing

### ISSUE THREAD

**Issue by KagaJiankui** [zhishixiang/tencent-push#7]
运行release的QQ.exe与git clone的QQ.py时log中均出现以下异常:
```log
[2022-04-19 10:21:39,281] ERROR in app: Exception on / [POST]
Traceback (most recent call last):
  File "D:\Anaconda\envs\tencent-push\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Anaconda\envs\tencent-push\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Anaconda\envs\tencent-push\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Anaconda\envs\tencent-push\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\Anaconda\envs\tencent-push\lib\site-packages\asgiref\sync.py", line 204, in __call__
    return call_result.result()
  File "D:\Anaconda\envs\tencent-push\lib\concurrent\futures\_base.py", line 437, in result
    return self.__get_result()
  File "D:\Anaconda\envs\tencent-push\lib\concurrent\futures\_base.py", line 389, in __get_result
    raise self._exception
  File "D:\Anaconda\envs\tencent-push\lib\site-packages\asgiref\sync.py", line 270, in main_wrap
    result = await self.awaitable(*args, **kwargs)
  File "d:\tencent-push\QQ.py", line 133, in recvMsg
    msg = msgFormat(msg)
UnboundLocalError: local variable 'msg' referenced before assignment
```

**Comment by zhishixiang** [comment]
更换release版本后是否还会出现以下情况

**Comment by KagaJiankui** [comment]
release版本出现如下的其他异常,但是该错误不影响消息接收
```log
[2022-04-20 07:58:47,561] ERROR in app: Exception on / [POST]
Traceback (most recent call last):
  File "flask\app.py", line 2077, in wsgi_app
  File "flask\app.py", line 1525, in full_dispatch_request
  File "flask\app.py", line 1523, in full_dispatch_request
  File "flask\app.py", line 1509, in dispatch_request
  File "asgiref\sync.py", line 204, in __call__
  File "concurrent\futures\_base.py", line 438, in result
  File "concurrent\futures\_base.py", line 390, in __get_result
  File "asgiref\sync.py", line 270, in main_wrap
  File "QQ.py", line 101, in recvMsg
  File "QQ.py", line 31, in msgFormat
NameError: name 're' is not defined
```

**Comment by zhishixiang** [comment]
请提供出现错误的release详细版本

**Comment by zhishixiang** [comment]
将在v0.9中修复
